[tox]
requires = tox>=4
env_list = py313,lint,type

[testenv]
allowlist_externals =
    uv
    pytest
deps =
    .[dev]
setenv =
    FLASK_ENV=pytest
    SECRET_KEY="MOCK_SECRET_KEY"
    SQLALCHEMY_DATABASE_URI=sqlite+pysqlite:///:memory:
    GLOBUS_AUTH_LOGOUT_URI="https://auth.globus.org/v2/web/logout"
    USER_SCOPES="openid profile email urn:globus:auth:scope:transfer.api.globus.org:all https://auth.globus.org/scopes/facd7ccc-c5f4-42aa-916b-a0e270e2c2a9/all https://auth.globus.org/scopes/eec9b274-0c81-4334-bdc2-54e90e689b9a/all"
    HOST="localhost:5328"
    NEXT_URL="http://localhost:3000"
    FLASK_RUN_HOST="localhost"
    FLASK_RUN_PORT="5328"
    AUTH_URL="https://backend.diamondhpc.ai"
commands = pytest -v --cov=diamond_backend --cov-report=xml --cov-report=term {posargs}
install_command = uv pip install {opts} {packages}
list_dependencies_command = uv pip list
package = wheel

[testenv:lint]
deps = ruff
commands =
    ruff check .
    ruff format --check .

[testenv:format]
deps = ruff
commands = ruff format .

[testenv:type]
deps = mypy
commands = mypy diamond_backend  --ignore-missing-imports
