"""initial schema

Revision ID: 97c3d7c7b8d2
Revises:
Create Date: 2026-09-23 15:53:57.295891

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97c3d7c7b8d2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoints",
        sa.Column("identity_id", sa.String(length=255), nullable=False),
        sa.Column("endpoint_name", sa.String(length=255), nullable=False),
        sa.Column("endpoint_host", sa.String(length=255), nullable=False),
        sa.Column("endpoint_uuid", sa.String(length=255), nullable=False),
        sa.Column("endpoint_status", sa.String(length=255), nullable=False),
        sa.Column("partitions", sa.JSON(), nullable=True),
        sa.Column("accounts", sa.JSON(), nullable=True),
        sa.Column("diamond_dir", sa.String(length=255), nullable=True),
        sa.Column("is_managed", sa.Boolean(), nullable=True),
        sa.Column("user_endpoint_config", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("identity_id", "endpoint_uuid"),
    )
    op.create_table(
        "profile",
        sa.Column("identity_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("institution", sa.Text(), nullable=True),
        sa.Column("is_initialized", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("identity_id"),
    )
    op.create_table(
        "container",
        sa.Column("container_task_id", sa.String(), nullable=True),
        sa.Column("container_status", sa.String(), nullable=True),
        sa.Column("identity_id", sa.String(length=255), nullable=True),
        sa.Column("base_image", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("dependencies", sa.Text(), nullable=True),
        sa.Column("environment", sa.Text(), nullable=True),
        sa.Column("commands", sa.Text(), nullable=True),
        sa.Column("endpoint_id", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("host", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["profile.identity_id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identity_id", sa.String(length=255), nullable=True),
        sa.Column("collection_uuid", sa.String(length=36), nullable=False),
        sa.Column("globus_path", sa.String(), nullable=False),
        sa.Column("system_path", sa.String(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("machine_name", sa.String(), nullable=False),
        sa.Column("dataset_name", sa.String(length=255), nullable=True),
        sa.Column("dataset_metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["profile.identity_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("batch_job_id", sa.String(), nullable=True),
        sa.Column("task_name", sa.String(), nullable=True),
        sa.Column("identity_id", sa.String(length=255), nullable=True),
        sa.Column("task_status", sa.String(), nullable=True),
        sa.Column("task_create_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("log_path", sa.String(), nullable=True),
        sa.Column("stdout_path", sa.String(), nullable=True),
        sa.Column("stderr_path", sa.String(), nullable=True),
        sa.Column("compute_endpoint_id", sa.String(), nullable=True),
        sa.Column("checkpoint_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["profile.identity_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("dataset")
    op.drop_table("container")
    op.drop_table("profile")
    op.drop_table("endpoints")
    # ### end Alembic commands ###
