name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract start command from railway.json
      id: railway-config
      run: echo "start_cmd=$(jq -r '.deploy.startCommand' railway.json)" >> $GITHUB_OUTPUT

    - name: Build with Nixpacks # (same as railway build process)
      uses: iloveitaly/github-action-nixpacks@main
      with:
        push: false
        tags: |
          ghcr.io/diamond-proj/diamond-admin-backend:${{ github.sha }}
          ghcr.io/diamond-proj/diamond-admin-backend:latest
        env:
          NIXPACKS_START_CMD="${{ steps.railway-config.outputs.start_cmd }}"
