name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Build with Nixpacks # (same as railway build process)
      uses: iloveitaly/github-action-nixpacks@main
      with:
        push: false
